name: test workflow

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: fribdaq/frib-buster-ci:v3.7
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: Create tarball
        run: tar -czf release-$GITHUB_REF_NAME-buster.tar.gz mine
      - name: Publish to release page
        run: |
          echo "ARCHIVE=$(ls *.tar.gz)" >> $GITHUB_ENV
          gh release create ${{ github.ref_name }} --title ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} $ARCHIVE
