name: test workflow

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: fribdaq/frib-buster-ci:v3.7
      options: --cpus 2
    steps:
      - uses: actions/checkout@v3
      - name: Create tarball
        run: |
         tar -czf release-$GITHUB_REF_NAME-buster.tar.gz mine
         mkdir build
         mv *.tar.gz build
      - name: Publish to release page
        uses: softprops/action-gh-release@latest
        with:
          files: build/*.tar.gz
          body: My Test
          name: My
