name: test workflow

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create tarball
        run: |
         tar -czf release-$GITHUB_REF_NAME-buster.tar.gz mine
         mkdir build
         mv *.tar.gz build
         echo "This is my body!" > haha
      - name: Upload tarball
        uses: actions/upload-artifact@v3
        with:
          name: thisversion
          path: build/*.tar.gz
      - name: Remove exiting one
        run: |
          rm -rf build
      - name: Working dir
        working-directory: ./build
        run: pwd
      - name: Download tarball
        uses: actions/download-artifact@v3
        with:
          name: thisversion
      - name: Change name
        run: |
          pwd
          cp build/release-$GITHUB_REF_NAME-buster.tar.gz build/ha.tar.gz
      - name: Publish to release page
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: build/*.tar.gz
          body_path: haha
          name: My
